import os
from dotenv import load_dotenv

load_dotenv()

GITHUB_APP_ID = os.getenv("GITHUB_APP_ID")
GITHUB_PRIVATE_KEY_PATH = os.getenv("GITHUB_PRIVATE_KEY_PATH")

MICROSOFT_CLIENT_ID = os.getenv("MICROSOFT_CLIENT_ID")
MICROSOFT_CLIENT_SECRET = os.getenv("MICROSOFT_CLIENT_SECRET")
MICROSOFT_TENANT_ID = os.getenv("MICROSOFT_TENANT_ID")

EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME")

# Collection Name
TEAMS_COLLECTION_NAME = "Teams-Posts"
DOCS_COLLECTION_NAME = "Documents"
GIT_COLLECTION_NAME = "Git-Activities"
EMAIL_COLLECTION_NAME = "Emails"